### ISSUE TITLE
CVAT Simplification Checklist

### ISSUE THREAD

**Issue by Vafilor** [onepanelio/core#453]
- [ ] Migration to make sure all params needed by update are in the workspace template for TF Object Detection and MaskRCNN
- [ ] Migration to make sure updated cvat image is used
- [ ] Migration to make sure labels are added to workflows that are cvat specific. `in: cvat`
